import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/imagemanagement">ImageManagement</Link>
        </li>
        <li>
          <Link to="/videolibrary">VideoLibrary</Link>
        </li>
        <li>
          <Link to="/contactus">ContactUs</Link>
        </li>
        <li>
          <Link to="/emaillogin">Emaillogin</Link>
        </li>
        <li>
          <Link to="/friendlist">FriendList</Link>
        </li>
        <li>
          <Link to="/share">Share</Link>
        </li>
        <li>
          <Link to="/hashtags">Hashtags</Link>
        </li>
        <li>
          <Link to="/activityfeed">ActivityFeed</Link>
        </li>
        <li>
          <Link to="/addfriends">AddFriends</Link>
        </li>
        <li>
          <Link to="/contactsharing">ContactSharing</Link>
        </li>
        <li>
          <Link to="/useraccount">UserAccount</Link>
        </li>
        <li>
          <Link to="/followers">Followers</Link>
        </li>
        <li>
          <Link to="/amazonpayintegration">AmazonPayIntegration</Link>
        </li>
        <li>
          <Link to="/googlepayintegration">GooglePayIntegration</Link>
        </li>
        <li>
          <Link to="/paypalintegration">PaypalIntegration</Link>
        </li>
        <li>
          <Link to="/paytmintegration">PaytmIntegration</Link>
        </li>
        <li>
          <Link to="/mobikwikintegration">MobikwikIntegration</Link>
        </li>
        <li>
          <Link to="/applepayintegration">ApplePayIntegration</Link>
        </li>
        <li>
          <Link to="/rupayintegration">RupayIntegration</Link>
        </li>
        <li>
          <Link to="/gocardlessintegration">GocardlessIntegration</Link>
        </li>
        <li>
          <Link to="/googlenewsintegration">GooglenewsIntegration</Link>
        </li>
        <li>
          <Link to="/googleadsenseintegration">GoogleAdsenseIntegration</Link>
        </li>
        <li>
          <Link to="/bhimupiintegration">BHIMUPIIntegration</Link>
        </li>
        <li>
          <Link to="/freechargeintegration">FreechargeIntegration</Link>
        </li>
        <li>
          <Link to="/intercomintegration">IntercomIntegration</Link>
        </li>
        <li>
          <Link to="/mixpanelintegration">MixpanelIntegration</Link>
        </li>
        <li>
          <Link to="/quickbooksintegration">QuickbooksIntegration</Link>
        </li>
        <li>
          <Link to="/outlookintegration">OutlookIntegration</Link>
        </li>
        <li>
          <Link to="/kekapayrollintegration">KekaPayrollIntegration</Link>
        </li>
        <li>
          <Link to="/beefreeintegration">BeefreeIntegration</Link>
        </li>
        <li>
          <Link to="/bluetoothintegration">BluetoothIntegration</Link>
        </li>
        <li>
          <Link to="/cardconnectintegration">CardconnectIntegration</Link>
        </li>
        <li>
          <Link to="/counterpartyintegration">CounterpartyIntegration</Link>
        </li>
        <li>
          <Link to="/customadvertisement">CustomAdvertisement</Link>
        </li>
        <li>
          <Link to="/disqusintegration">DisqusIntegration</Link>
        </li>
        <li>
          <Link to="/hubspotintegration">HubspotIntegration</Link>
        </li>
        <li>
          <Link to="/docusignintegration">DocusignIntegration</Link>
        </li>
        <li>
          <Link to="/integrateandroidwearuilibrary">
            IntegrateAndroidWearUILibrary
          </Link>
        </li>
        <li>
          <Link to="/scheduleonce">ScheduleOnce</Link>
        </li>
        <li>
          <Link to="/wordpressintegration">WordpressIntegration</Link>
        </li>
        <li>
          <Link to="/mailchimpintegration">MailchimpIntegration</Link>
        </li>
        <li>
          <Link to="/salesforceintegration">SalesforceIntegration</Link>
        </li>
        <li>
          <Link to="/schemaorgintegration">SchemaorgIntegration</Link>
        </li>
        <li>
          <Link to="/sendyintegration">SendyIntegration</Link>
        </li>
        <li>
          <Link to="/skypeintegration">SkypeIntegration</Link>
        </li>
        <li>
          <Link to="/stellarintegration">StellarIntegration</Link>
        </li>
        <li>
          <Link to="/stripeintegration">StripeIntegration</Link>
        </li>
        <li>
          <Link to="/twiliointegration">TwilioIntegration</Link>
        </li>
        <li>
          <Link to="/freshdeskintegration">FreshdeskIntegration</Link>
        </li>
        <li>
          <Link to="/gettyimagesintegration">GettyImagesIntegration</Link>
        </li>
        <li>
          <Link to="/bluetooth">Bluetooth</Link>
        </li>
        <li>
          <Link to="/radiointegration">RadioIntegration</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
